name: co19_finalization_registry
description: co19 tests for Dart Finalization Registry feature

# This tests isn't intended for publishing on pub.dev.
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  ffi: ^1.0.0